name: Prepare for Release
on:
  workflow_dispatch: 
    inputs:
      tag:
        description: "Tag for the release (example: 1.2.3)"
        required: true
        default: "1.0.0"

env:
  PR_NAME: 'ShinRyuModManager ${{ github.event.inputs.tag }}'
  PR_TAG: ${{ github.event.inputs.tag }}
      
jobs:
  build-parless:
    runs-on: windows-latest
    permissions: 
      contents: write
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
        with:
          repository: SRMM-Studio/YakuzaParless
          path: external/parless
          submodules: recursive

      - name: Install Premake 5
        uses: abel0b/setup-premake@de7d79047789622064f7a2d251e929fadd166707 # v2.4
        with:
          version: "5.0.0-beta2"

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@79dac248aac9d0059f86eae9d8b5bfab4e95e97c # v4.0.0
        with:
          arch: x64
      
      - name: Generate VS Project
        working-directory: external/parless
        run: premake5 vs2022
        
      - name: Build Parless
        working-directory: external/parless/build
        run: msbuild YakuzaParless.sln /p:Configuration=Release /p:Platform=Win64
        
      - name: Upload Parless Artifact
        id: upload-unsigned-parless
        uses: actions/upload-artifact@v7
        with: 
          name: 'ParlessArtifact-unsigned'
          path: external\parless\build\bin\Win64\Release\YakuzaParless.asi
          if-no-files-found: 'error'
          retention-days: 1
          compression-level: 0
          overwrite: true
          
      - name: Sign Parless
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ secrets.SIGNPATH_ORGANIZATION_ID }}'
          project-slug: 'ShinRyuModManager'
          signing-policy-slug: 'test-signing'
          artifact-configuration-slug: 'parless'
          github-artifact-id: '${{ steps.upload-unsigned-parless.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: 'external\parless\build\bin\Win64\Release\signed'
  
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      
    needs: build-parless
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7
          
      - name: Download Parless Artifact
        uses: actions/download-artifact@v7
        with: 
          path: '${{ runner.temp }}/external'
          
      - name: Download version.dll
        run: |
          curl -L https://github.com/SRMM-Studio/srmm-distrib/raw/refs/heads/main/Native/version.dll -o $RUNNER_TEMP/external/version.dll
          echo "79c74febb21082474c5dfff54fa4a2514b1fc3b6e02245cf491eb6f2d055bfe5  $RUNNER_TEMP/external/version.dll" | sha256sum --check
      
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        
      - name: Create Draft Release
        id: create_release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21
        with:
          tag: "v${{ env.PR_TAG }}"
          name: ${{ env.PR_NAME }}
          draft: true
          generateReleaseNotesPreviousTag: true
        
      - name: Build SRMM Versions
        run: ./Scripts/build.sh
        
      - name: Prepare Windows Binaries for Signing
        run: |
          cd "${{ github.workspace }}/dist/srmm"
          zip -r "${{ runner.temp }}/to-sign.zip" windows/ShinRyuModManager.exe windows-slim/ShinRyuModManager.exe
          
      - name: Upload SRMM Artifact
        id: upload-unsigned-srmm
        uses: actions/upload-artifact@v7
        with:
          name: 'SRMM-unsigned'
          path: ${{ runner.temp }}/to-sign.zip
          if-no-files-found: 'error'
          retention-days: 1
          compression-level: 0
          overwrite: true
          
      - name: Sign SRMM Binaries
        uses: signpath/github-action-submit-signing-request@v2
        with:
          api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
          organization-id: '${{ secrets.SIGNPATH_ORGANIZATION_ID }}'
          project-slug: 'ShinRyuModManager'
          signing-policy-slug: 'test-signing'
          artifact-configuration-slug: 'srmm-exe'
          github-artifact-id: '${{ steps.upload-unsigned-srmm.artifact-id }}'
          wait-for-completion: true
          output-artifact-directory: '${{ runner.temp }}/signed'
          
      - name: Replace for Packaging
        run: |
          unzip -o "${{ runner.temp }}/signed/to-sign.zip" -d "${{ runner.temp }}/signed-output"
          cp "${{ runner.temp }}/signed-out/windows/ShinRyuModManager.exe" dist/srmm/windows/ShinRyuModManager.exe
          cp "${{ runner.temp }}/signed-out/windows-slim/ShinRyuModManager.exe" dist/srmm/windows-slim/ShinRyuModManager.exe
      
      - name: Package Binaries
        run: ./Scripts/package.sh -s $PR_TAG
          
      - name: Upload SRMM Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
        run: |
          for file in ${{ github.workspace }}/dist/srmm/out/*; do
            name=$(basename "$file")
            mime=$(file --brief --mime-type "$file")
            echo "Uploading $name ($mime)"
            curl \
              -X POST \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: $mime" \
              --data-binary @"$file" \
              --no-progress-meter \
              "${UPLOAD_URL%%\{*}?name=$name" > /dev/null
          done
